=== aagahi/PSUG-Challenge-USI-2011/test-data/gamesession.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.usi.com" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:usi="http://www.usi.com">

    
    <xsd:complexType name="questiontype">
    	<xsd:sequence>
    		<xsd:element name="question" type="usi:question" minOccurs="1" maxOccurs="20"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="question">
    	<xsd:sequence>
    		<xsd:element name="label" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="choice" type="xsd:string" maxOccurs="4" minOccurs="4"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="goodchoice" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:attribute name="goodchoice" type="xsd:string"></xsd:attribute>


    
    <xsd:complexType name="parametertype">
    	<xsd:sequence>
    		<xsd:element name="logintimeout" type="xsd:int" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="synchrotime" type="xsd:int" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="nbusersthreshold" type="xsd:int" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="questiontimeframe" type="xsd:int" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="nbquestions" type="xsd:int" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="flushusertable" type="xsd:boolean" minOccurs="1" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="trackeduseridmail" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="gamesession" type="usi:sessiontype"></xsd:element>

    <xsd:complexType name="sessiontype">
    	<xsd:sequence>
    		<xsd:element name="questions" type="usi:questiontype" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="parameters" type="usi:parametertype" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== aagahi/PSUG-Challenge-USI-2011/test-data/gamesession.xml
<?xml version="1.0" encoding="UTF-8"?>
<usi:gamesession xmlns:usi="http://www.usi.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.usi.com gamesession.xsd ">
  <usi:questions>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
    <usi:question goodchoice="0">
      <usi:label>usi:label</usi:label>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
      <usi:choice>usi:choice</usi:choice>
    </usi:question>
  </usi:questions>
  <usi:parameters>
    <usi:logintimeout>0</usi:logintimeout>
    <usi:synchrotime>0</usi:synchrotime>
    <usi:nbusersthreshold>0</usi:nbusersthreshold>
    <usi:questiontimeframe>0</usi:questiontimeframe>
    <usi:nbquestions>0</usi:nbquestions>
    <usi:flushusertable>true</usi:flushusertable>
    <usi:trackeduseridmail>usi:trackeduseridmail</usi:trackeduseridmail>
  </usi:parameters>
</usi:gamesession>
